name: Build and push Docker image

on:
  push:
    branches:
    - master
  pull_request:
  schedule:
    - cron: '0 2 * * 0'
  workflow_dispatch:

env:
  CI: true
  DOCKER_BUILDKIT: 1

jobs:
  generate:
    strategy:
      matrix:
        include:
          - runner: ubuntu-24.04
            architecture: i686
            package-manager: apt
          - runner: ubuntu-24.04
            architecture: x86_64
            package-manager: apt
          - runner: ubuntu-24.04-arm
            architecture: arm
            package-manager: apt
          - runner: ubuntu-24.04-arm
            architecture: aarch64
            package-manager: apt
          - runner: ubuntu-24.04
            architecture: i686
            package-manager: pacman
          - runner: ubuntu-24.04
            architecture: x86_64
            package-manager: pacman
          - runner: ubuntu-24.04-arm
            architecture: arm
            package-manager: pacman
          - runner: ubuntu-24.04-arm
            architecture: aarch64
            package-manager: pacman
    runs-on: ${{ matrix.runner }}
    steps:

    - name: Set variables
      run: |
        echo "TERMUX_ARCH=${{ matrix.architecture }}" >> $GITHUB_ENV
        echo "TERMUX_PACKAGE_MANAGER=${{ matrix.package-manager }}" >> $GITHUB_ENV
        if [ ${{ matrix.package-manager }} = apt ]; then
          echo "TERMUX_DOCKER__IMAGE_NAME=termux/termux-docker" >> $GITHUB_ENV
        elif [ ${{ matrix.package-manager }} = pacman ]; then
          echo "TERMUX_DOCKER__IMAGE_NAME=termux/termux-docker-pacman" >> $GITHUB_ENV
        fi

    - name: Clone repository
      uses: actions/checkout@v6

    - name: Build image
      run: ./generate.sh

    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request' && github.repository == 'termux/termux-docker'
      uses: docker/login-action@v3
      with:
        username: grimler
        password: ${{ secrets.GRIMLER_DOCKER_TOKEN }}

    - name: Push to Docker Hub
      if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request' && github.repository == 'termux/termux-docker'
      run: |
        docker push ${{ env.TERMUX_DOCKER__IMAGE_NAME }}:${{ env.TERMUX_ARCH }}
        if [ ${{ env.TERMUX_ARCH }} = x86_64 ]; then
          docker push ${{ env.TERMUX_DOCKER__IMAGE_NAME }}:latest
        fi

    - name: Export container as tar archive
      if: always()
      run: |
        docker run \
          --name termux-docker-${{ env.TERMUX_PACKAGE_MANAGER }}-${{ env.TERMUX_ARCH }} \
          ${{ env.TERMUX_DOCKER__IMAGE_NAME }}:${{ env.TERMUX_ARCH }} \
          uname -a
        docker stop termux-docker-${{ env.TERMUX_PACKAGE_MANAGER }}-${{ env.TERMUX_ARCH }}
        docker export -o termux-docker-${{ env.TERMUX_PACKAGE_MANAGER }}-${{ env.TERMUX_ARCH }}.tar \
          termux-docker-${{ env.TERMUX_PACKAGE_MANAGER }}-${{ env.TERMUX_ARCH }}
        sha256sum termux-docker-${{ env.TERMUX_PACKAGE_MANAGER }}-${{ env.TERMUX_ARCH }}.tar

    - name: Store tar archive
      if: always()
      uses: actions/upload-artifact@v5
      with:
        name: termux-docker-${{ env.TERMUX_PACKAGE_MANAGER }}-${{ env.TERMUX_ARCH }}-${{ github.sha }}
        path: termux-docker-${{ env.TERMUX_PACKAGE_MANAGER }}-${{ env.TERMUX_ARCH }}.tar
